# Generated by Django 3.1.3 on 2021-08-03 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bannerTitle', models.CharField(blank=True, max_length=20)),
                ('descriptions', models.CharField(blank=True, max_length=20)),
                ('bannerImages', models.FileField(null=True, upload_to='Upload_Images/adminSignature/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AddressListedBYUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, max_length=100)),
                ('landmark', models.CharField(blank=True, max_length=50)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('pincode', models.CharField(blank=True, max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AddToCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=20)),
                ('remarks', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bannerTitle', models.CharField(blank=True, max_length=20)),
                ('bannerImages', models.FileField(null=True, upload_to='Upload_Images/adminSignature/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EnquiryForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactNo', models.CharField(blank=True, max_length=10, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EnquiryFormData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('state', models.CharField(blank=True, max_length=30)),
                ('city', models.CharField(blank=True, max_length=30)),
                ('address', models.TextField(blank=True)),
                ('remarks', models.TextField(blank=True)),
                ('status', models.CharField(blank=True, default='pending', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productCategoryName', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobileNO', models.CharField(blank=True, max_length=12, unique=True)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('address', models.TextField(blank=True, max_length=500)),
                ('user_image', models.FileField(blank=True, null=True, upload_to='Upload_Images/UserImages/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductsListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(blank=True, max_length=50)),
                ('productCoverImages', models.FileField(blank=True, null=True, upload_to='Upload_Images/productImages/')),
                ('productImages_one', models.FileField(blank=True, null=True, upload_to='Upload_Images/productImages/')),
                ('productImages_two', models.FileField(blank=True, null=True, upload_to='Upload_Images/productImages/')),
                ('productImages_three', models.FileField(blank=True, null=True, upload_to='Upload_Images/productImages/')),
                ('productImages_four', models.FileField(blank=True, null=True, upload_to='Upload_Images/productImages/')),
                ('productImages_five', models.FileField(blank=True, null=True, upload_to='Upload_Images/productImages/')),
                ('productImages_six', models.FileField(blank=True, null=True, upload_to='Upload_Images/productImages/')),
                ('productImages_sevenr', models.FileField(blank=True, null=True, upload_to='Upload_Images/productImages/')),
                ('productDescription', models.TextField(blank=True)),
                ('productDimension', models.CharField(blank=True, max_length=50)),
                ('productPrice', models.CharField(blank=True, max_length=10)),
                ('productQuantity', models.CharField(blank=True, max_length=10)),
                ('productDisplay', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('productCategory', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='fourYouthAPI.productscategory')),
            ],
        ),
        migrations.AddConstraint(
            model_name='productscategory',
            constraint=models.UniqueConstraint(fields=('productCategoryName',), name='ProductsCategory Listing'),
        ),
        migrations.AddField(
            model_name='enquiryformdata',
            name='enquiryfk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='fourYouthAPI.enquiryform'),
        ),
        migrations.AddField(
            model_name='enquiryformdata',
            name='productfk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='fourYouthAPI.productslisting'),
        ),
        migrations.AddField(
            model_name='enquiryformdata',
            name='userfk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='fourYouthAPI.userprofile'),
        ),
        migrations.AddField(
            model_name='addtocart',
            name='productfk',
            field=models.ManyToManyField(to='fourYouthAPI.ProductsListing'),
        ),
        migrations.AddField(
            model_name='addtocart',
            name='userfk',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='addresslistedbyuser',
            name='userInstance',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='fourYouthAPI.userprofile'),
        ),
        migrations.AddConstraint(
            model_name='userprofile',
            constraint=models.UniqueConstraint(fields=('mobileNO',), name='UserProfile Constraint'),
        ),
        migrations.AddConstraint(
            model_name='productslisting',
            constraint=models.UniqueConstraint(fields=('productName',), name='Product Listing'),
        ),
        migrations.AddConstraint(
            model_name='addresslistedbyuser',
            constraint=models.UniqueConstraint(fields=('address', 'landmark', 'state', 'pincode'), name='AddressListedBYUser Constraints'),
        ),
    ]
