# Generated by Django 3.1.3 on 2021-08-03 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fourYouthAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtocart',
            name='userfk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
