# Generated by Django 3.1.3 on 2021-08-05 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fourYouthAPI', '0002_auto_20210803_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtocart',
            name='productQuantity',
            field=models.CharField(blank=True, default='1', max_length=50),
        ),
    ]
