# Generated by Django 3.1.3 on 2021-08-05 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fourYouthAPI', '0003_addtocart_productquantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addtocart',
            name='productfk',
        ),
        migrations.AddField(
            model_name='addtocart',
            name='productfk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='fourYouthAPI.productslisting'),
        ),
    ]
