# Generated by Django 3.1.3 on 2021-08-10 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fourYouthAPI', '0006_orderdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='orderID',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
