# Generated by Django 3.1.3 on 2021-08-20 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fourYouthAPI', '0007_auto_20210810_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='addresslistedbyuser',
            name='contact',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='addresslistedbyuser',
            name='district',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='addresslistedbyuser',
            name='fullname',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
