# Generated by Django 3.1.3 on 2021-08-31 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fourYouthAPI', '0008_auto_20210820_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productslisting',
            name='productPrice',
            field=models.IntegerField(blank=True),
        ),
    ]
