# Generated by Django 3.1.3 on 2021-09-02 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fourYouthAPI', '0010_auto_20210901_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddToWishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('productfk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fourYouthAPI.productslisting')),
                ('userfk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='addtowishlist',
            constraint=models.UniqueConstraint(fields=('productfk', 'userfk'), name='AddToWishlist Constraints'),
        ),
    ]
