# Generated by Django 3.1.3 on 2021-09-03 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fourYouthAPI', '0011_auto_20210902_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpdbmodel',
            name='otpStatus',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
