# Generated by Django 3.1.3 on 2021-09-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fourYouthAPI', '0012_otpdbmodel_otpstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpdbmodel',
            name='otpStatus',
            field=models.BooleanField(default=True),
        ),
    ]
